// <auto-generated />
namespace SAM.Taskboard.DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedCustomRoleToInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedCustomRoleToInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201905161057276_changedCustomRoleToInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
