// <auto-generated />
namespace SAM.Taskboard.DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class byte_img_to_base64_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(byte_img_to_base64_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201906041639483_byte[]_img_to_base64_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
