// <auto-generated />
namespace SAM.Taskboard.DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_comments_datetime3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_comments_datetime3));
        
        string IMigrationMetadata.Id
        {
            get { return "201906111724513_added_comments_datetime3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
