// <auto-generated />
namespace SAM.Taskboard.DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removed_teams : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_teams));
        
        string IMigrationMetadata.Id
        {
            get { return "201905150729160_removed_teams"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
